name: Archive README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  archive-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy README content
        run: cp README.md Q1_archive_README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Q1_archive_README.md
          git commit -m "Archive README content"
          git push
