name: Archive README avec informations supplémentaires

on: [push]

permissions:
  contents: write

jobs:
  create-and-push-enhanced-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Création du fichier Q2_archive_README.md
        run: |
          echo "Nom et prénom: Antunes Célia" > Q2_archive_README.md
          echo "Date et heure d'exécution: $(date '+%Y-%m-%d %H:%M:%S')" >> Q2_archive_README.md
          echo "" >> Q2_archive_README.md
          echo "Contenu du README.md original:" >> Q2_archive_README.md
          echo "--------------------------------" >> Q2_archive_README.md
          cat README.md >> Q2_archive_README.md

      - name: Configuration de Git
        run: |
          git config --global user.name "Celiants"
          git config --global user.email "antunes.celia2004@gmail.com"

      - name: Commit et push
        run: |
          git add Q2_archive_README.md
          git commit -m "Ajout de Q2_archive_README.md avec informations supplémentaires"
          git push
