name: Créer Q3_archive_java.txt

on: [push]

permissions:
  contents: write

jobs:
  create-and-push-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Création du fichier Q3_archive_java.txt
        run: |
          echo "Nom et prénom: Antunes Célia" > Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          echo "Contenu du fichier Q3.java:" >> Q3_archive_java.txt
          echo "--------------------------------" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      - name: Configuration de Git
        run: |
          git config --global user.name "Celiants"
          git config --global user.email "antunes.celia2004@gmail.com"

      - name: Commit et push
        run: |
          git add Q3_archive_java.txt
          git commit -m "Ajout de Q3_archive_java.txt"
          git push
