name: Créer Q6_archive_date.txt et Q6_différences.txt

on: [push]

permissions:
  contents: write

jobs:
  create-and-push-q6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Création des fichiers Q6_archive_<date>.txt et Q6_différences.txt
        run: |
          # Obtenir la date au format JJ-MM-AAAA-HHMMSS
          DATE=$(date +'%d-%m-%Y-%H%M%S')

          # Définir les noms des fichiers
          ARCHIVE_FILE="Q6_archive_${DATE}.txt"
          PREVIOUS_ARCHIVE_FILE=$(ls Q6_archive_*.txt 2>/dev/null | tail -n 1)
          DIFF_FILE="Q6_différences.txt"

          # Ajouter les informations dans le fichier Q6_archive_<date>.txt
          echo "Antunes Célia" > $ARCHIVE_FILE
          echo "" >> $ARCHIVE_FILE
          echo "Contenu du fichier Q6.java :" >> $ARCHIVE_FILE
          cat Q6.java >> $ARCHIVE_FILE
          echo "" >> $ARCHIVE_FILE
          echo "Statistiques de Q6.java :" >> $ARCHIVE_FILE
          wc Q6.java >> $ARCHIVE_FILE

          # Comparaison avec le fichier précédent (si existant)
          if [ -f "$PREVIOUS_ARCHIVE_FILE" ]; then
            diff "$PREVIOUS_ARCHIVE_FILE" "$ARCHIVE_FILE" > $DIFF_FILE || true
          else
            echo "Aucune différence détectée (première version)." > $DIFF_FILE
          fi

      - name: Configuration de Git
        run: |
          git config --global user.name "Celiants"
          git config --global user.email "antunes.celia2004@gmail.com"

      - name: Commit et push
        run: |
          git add Q6_archive_*.txt Q6_différences.txt
          git commit -m "Ajout des fichiers Q6_archive et Q6_différences"
          git push
