name: Créer Q6_archive_date.txt et Q6_différences.txt

on: [push]

permissions:
  contents: write

jobs:
  create-and-push-archives:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Création du fichier Q6_archive_date.txt
        run: |
          DATE=$(date '+%d-%m-%Y-%H%M%S')
          echo "Nom et prénom: Antunes Célia" > Q6_archive_${DATE}.txt
          echo "" >> Q6_archive_${DATE}.txt
          echo "Contenu du fichier Q6.java:" >> Q6_archive_${DATE}.txt
          echo "--------------------------------" >> Q6_archive_${DATE}.txt
          cat Q6.java >> Q6_archive_${DATE}.txt
          echo "" >> Q6_archive_${DATE}.txt
          echo "Taille du fichier Q6.java:" >> Q6_archive_${DATE}.txt
          wc -c -l Q6.java >> Q6_archive_${DATE}.txt

      - name: Création du fichier Q6_différences.txt
        run: |
          DATE=$(date '+%d-%m-%Y-%H%M%S')
          PREVIOUS_FILE=$(ls -t Q6_archive_*.txt | sed -n 2p)
          if [ -n "$PREVIOUS_FILE" ]; then
            diff "$PREVIOUS_FILE" "Q6_archive_${DATE}.txt" > Q6_différences.txt || true
          else
            echo "Pas de fichier précédent pour comparer." > Q6_différences.txt
          fi

      - name: Configuration de Git
        run: |
          git config --global user.name "Celiants"
          git config --global user.email "antunes.celia2004@gmail.com"

      - name: Commit et push
        run: |
          DATE=$(date '+%d-%m-%Y-%H%M%S')
          git add Q6_archive_${DATE}.txt Q6_différences.txt
          git commit -m "Ajout de Q6_archive_${DATE}.txt et Q6_différences.txt"
          git pull -rebase
          git push
